---

resources:
  # Repo to pull for building image
  - name: personal-website-repo-master
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/personal-website.git
      branch: master

  - name: personal-website-repo-version
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/personal-website.git
      branch: master
      paths:
        - version

  # Where we will push the image to
  - name: docker-hub-repo-latest
    type: registry-image
    icon: docker
    source:
      repository: flipenergy/flipenergy
      username: ((docker_hub_username))
      password: ((docker_hub_password))
      tag: latest

  - name: docker-hub-repo-stable
    type: registry-image
    icon: docker
    source:
      repository: flipenergy/flipenergy
      username: ((docker_hub_username))
      password: ((docker_hub_password))
      tag: stable

## Latest image jobs
jobs:
  - name: build-and-push-latest-image
    public: false
    serial: true
    plan:
      - get: personal-website-repo-master
        trigger: true

      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task

          inputs:
            - name: personal-website-repo-master

          outputs:
            - name: image

          params:
            CONTEXT: personal-website-repo-master
          run:
            path: build

      - put: docker-hub-repo-latest
        params:
          image: image/image.tar

## Release image job
  - name: build-and-push-release-image
    public: false
    serial: true
    plan:
      - get: personal-website-repo-version
        trigger: true

      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task

          inputs:
            - name: personal-website-repo-version

          outputs:
            - name: image

          params:
            CONTEXT: personal-website-repo-version
          run:
            path: build

      - put: docker-hub-repo-stable
        params:
          image: image/image.tar
          additional_tags: personal-website-repo-version/version
