resource_types:
  - *webhook-resource-type

resources:
  - *discord

  # Repo to pull for building image
  - name: personal-website-version-bump
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/personal-website.git
      branch: master
      username: ((github_username))
      password: ((github_password))
  - *concourse-pipelines-repo

  # Where we will push the image to
  - name: docker-hub-repo
    type: registry-image
    icon: docker
    source:
      repository: flipenergy/flipenergy
      username: ((docker_hub_username))
      password: ((docker_hub_password))
      tag: latest

jobs:
  - name: build-and-push-image
    serial: true
    plan:
      - get: personal-website-version-bump
        trigger: true

      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource: *oci-build-image-resource

          inputs:
            - name: personal-website-version-bump

          outputs:
            - name: image

          params:
            CONTEXT: personal-website-version-bump
          run:
            path: build

      - put: docker-hub-repo
        params:
          image: image/image.tar
          additional_tags: personal-website-version-bump/version

    on_error: *notify-failure
    on_failure: *notify-failure

  - name: deploy-website-to-k8s
    serial: true
    plan:
      - in_parallel:
        - get: personal-website-version-bump
          passed: [build-and-push-image]
        - get: docker-hub-repo
          trigger: true
          passed: [build-and-push-image]
        - get: concourse-pipelines-repo

      - task: get-secret-key
        config:
          platform: linux
          image_resource: *bitwarden-cli-image-resource

          inputs:
            - name: personal-website-version-bump
            - name: concourse-pipelines-repo

          outputs:
            - name: personal-website-version-bump
            - name: concourse-pipelines-repo
            - name: secrets

          params:
            BW_ITEM: ((bitwarden_item))
            BW_SERVER: ((bitwarden_server))
            BW_USERNAME: ((bitwarden_username))
            BW_PASSWORD: ((bitwarden_password))

          run:
            path: concourse-pipelines-repo/common/scripts/get_secret_key.sh

      - task: deploy-to-k8s
        config:
          platform: linux
          image_resource: *helmsman-image-resource

          inputs:
            - name: personal-website-version-bump
            - name: concourse-pipelines-repo
            - name: secrets

          run:
            path: concourse-pipelines-repo/personal_website/deploy_to_k8s.sh

    on_success: *notify-success
    on_error: *notify-failure
    on_failure: *notify-failure
