# begin resource templates
resource_options: &resource_options
  type: registry-image
  icon: docker
  check_every: 30m
# end resource templates

resource_types:
  - *webhook-resource-type

resources:
  - *discord-info

  - name: &ihatemoney_resource ihatemoney-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: ihatemoney/ihatemoney

  - name: &oci_resource oci-build-task-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: concourse/oci-build-task

  - name: &owncast_resource owncast-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: gabekangas/owncast

  - name: &syncthing_resource syncthing-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: syncthing/syncthing

  - name: &vaultwarden_resource vaultwarden-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: vaultwarden/server

  - name: &wikijs_resource wikijs-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: requarks/wiki

# begin job templates
get_options: &get_options
  params:
    skip_download: true
  trigger: true

build_message_config: &build_message_config
  platform: linux
  image_resource: *alpine-image-resource
  outputs:
    - name: message
  run:
    path: sh
    args:
      - -ec
      - >
        echo ":new: **[${IMAGE_NAME}" 'image tag](${BUILD_URL})**' $(cat ${RESOURCE_DIR}/tag) > message/message.txt

discord_notification: &discord_notification
  put: discord-info
  params:
    message_file: /tmp/build/put/message/message.txt
# end job templates

jobs:
  - name: ihatemoney
    plan:
      - get: *ihatemoney_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *ihatemoney_resource
          params:
            IMAGE_NAME: ihatemoney
            RESOURCE_DIR: *ihatemoney_resource
      - *discord_notification

  - name: oci-build-task
    plan:
      - get: *oci_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *oci_resource
          params:
            IMAGE_NAME: OCI-build
            RESOURCE_DIR: *oci_resource
      - *discord_notification

  - name: owncast
    plan:
      - get: *owncast_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *owncast_resource
          params:
            IMAGE_NAME: Owncast
            RESOURCE_DIR: *owncast_resource
      - *discord_notification

  - name: syncthing
    plan:
      - get: *syncthing_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *syncthing_resource
          params:
            IMAGE_NAME: Syncthing
            RESOURCE_DIR: *syncthing_resource
      - *discord_notification

  - name: vaultwarden
    plan:
      - get: *vaultwarden_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *vaultwarden_resource
          params:
            IMAGE_NAME: Vaultwarden
            RESOURCE_DIR: *vaultwarden_resource
      - *discord_notification

  - name: wikijs
    plan:
      - get: *wikijs_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *wikijs_resource
          params:
            IMAGE_NAME: WikiJS
            RESOURCE_DIR: *wikijs_resource
      - *discord_notification
