# begin resource templates
resource_options: &resource_options
  type: registry-image
  icon: docker
  check_every: 30m
# end resource templates

resource_types:
  - *webhook-resource-type

resources:
  - *discord-image

  - name: &cryptofolio_resource cryptofolio-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: xtrendence/cryptofolio

  - name: &flatnotes_resource flatnotes-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: dullage/flatnotes

  - name: &ihatemoney_resource ihatemoney-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: ihatemoney/ihatemoney

  - name: &jellyfin_resource jellyfin-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: jellyfin/jellyfin

  - name: &kube_resource kube-ops-view-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: hjacobs/kube-ops-view

  - name: &nextcloud_resource nextcloud-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: nextcloud
      variant: apache

  - name: &paperless_resource paperless-ngx-docker-repo
    <<: *resource_options
    source:
      repository: ghcr.io/paperless-ngx/paperless-ngx

  - name: &oci_resource oci-build-task-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: concourse/oci-build-task

  - name: &owncast_resource owncast-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: gabekangas/owncast

  - name: &soft_serve_resource soft-serve-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: charmcli/soft-serve

  - name: &vaultwarden_resource vaultwarden-docker-repo
    <<: *resource_options
    source:
      <<: *docker-creds
      repository: vaultwarden/server

# begin job templates
get_options: &get_options
  params:
    skip_download: true
  trigger: true

build_message_config: &build_message_config
  platform: linux
  image_resource: *alpine-image-resource
  outputs:
    - name: message
  run:
    path: sh
    args:
      - -ec
      - >
        echo ":new: **[${IMAGE_NAME}" 'image tag](${BUILD_URL})**' $(cat ${RESOURCE_DIR}/tag) "[release notes](${RELEASE_URL})"> message/message.txt

discord_notification: &discord_notification
  put: discord-image
  params:
    message_file: /tmp/build/put/message/message.txt
# end job templates

jobs:
  - name: cryptofolio
    plan:
      - get: *cryptofolio_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *cryptofolio_resource
          params:
            IMAGE_NAME: cryptofolio
            RELEASE_URL: https://github.com/Xtrendence/Cryptofolio/releases
            RESOURCE_DIR: *cryptofolio_resource
      - *discord_notification

  - name: flatnotes
    plan:
      - get: *flatnotes_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *flatnotes_resource
          params:
            IMAGE_NAME: flatnotes
            RELEASE_URL: https://github.com/Dullage/flatnotes/releases
            RESOURCE_DIR: *flatnotes_resource
      - *discord_notification

  - name: ihatemoney
    plan:
      - get: *ihatemoney_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *ihatemoney_resource
          params:
            IMAGE_NAME: ihatemoney
            RELEASE_URL: https://github.com/spiral-project/ihatemoney/releases
            RESOURCE_DIR: *ihatemoney_resource
      - *discord_notification

  - name: jellyfin
    plan:
      - get: *jellyfin_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *jellyfin_resource
          params:
            IMAGE_NAME: Jellyfin
            RELEASE_URL: https://github.com/jellyfin/jellyfin/releases
            RESOURCE_DIR: *jellyfin_resource
      - *discord_notification

  - name: kube-ops-view
    plan:
      - get: *kube_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *kube_resource
          params:
            IMAGE_NAME: kube-ops-view
            RELEASE_URL: https://codeberg.org/hjacobs/kube-ops-view/tags
            RESOURCE_DIR: *kube_resource
      - *discord_notification

  - name: nextcloud
    plan:
      - get: *nextcloud_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *nextcloud_resource
          params:
            IMAGE_NAME: nextcloud
            RELEASE_URL: https://nextcloud.com/changelog/#latest24
            RESOURCE_DIR: *nextcloud_resource
      - *discord_notification

  - name: paperless-ngx
    plan:
      - get: *paperless_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *paperless_resource
          params:
            IMAGE_NAME: paperless-ngx
            RELEASE_URL: https://github.com/paperless-ngx/paperless-ngx/releases
            RESOURCE_DIR: *paperless_resource
      - *discord_notification

  - name: oci-build-task
    plan:
      - get: *oci_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *oci_resource
          params:
            IMAGE_NAME: OCI-build
            RELEASE_URL: https://github.com/concourse/oci-build-task/releases
            RESOURCE_DIR: *oci_resource
      - *discord_notification

  - name: owncast
    plan:
      - get: *owncast_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *owncast_resource
          params:
            IMAGE_NAME: Owncast
            RELEASE_URL: https://github.com/owncast/owncast/releases
            RESOURCE_DIR: *owncast_resource
      - *discord_notification

  - name: soft-serve
    plan:
      - get: *soft_serve_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *soft_serve_resource
          params:
            IMAGE_NAME: soft-serve
            RELEASE_URL: https://github.com/charmbracelet/soft-serve/releases
            RESOURCE_DIR: *soft_serve_resource
      - *discord_notification

  - name: vaultwarden
    plan:
      - get: *vaultwarden_resource
        <<: *get_options

      - task: build-message
        config:
          <<: *build_message_config
          inputs:
            - name: *vaultwarden_resource
          params:
            IMAGE_NAME: Vaultwarden
            RELEASE_URL: https://github.com/dani-garcia/vaultwarden/releases
            RESOURCE_DIR: *vaultwarden_resource
      - *discord_notification
