# begin resource templates
resource_options: &resource_options
  type: time
  icon: timer-outline
  check_every: 10m

resource_source: &resource_source
  start: 8:00 AM
  stop: 9:30 PM
  location: America/Vancouver
# end resource templates

resource_types:
  - *webhook-resource-type

resources:
  - name: discord-healthy-habits
    type: webhook-resource-type
    icon: bell
    source:
        adapter: DiscordAdapter
        url: ((discord_healthy_habits_webhook_url))
    check_every: never

  - name: &hourly hourly
    <<: *resource_options
    source:
      interval: 1h
      <<: *resource_source

  - name: &two_hourly two-hourly
    <<: *resource_options
    source:
      interval: 2h
      <<: *resource_source

# begin job templates
get_options: &get_options
  trigger: true
# end job templates

jobs:
  - name: drink-water
    plan:
      - get: *hourly
        <<: *get_options

      - put: discord-healthy-habits
        params:
          message: "**DRINK WATER!** :droplet:"

  - name: get-up-and-move
    plan:
      - get: *two_hourly
        <<: *get_options

      - put: discord-healthy-habits
        params:
          message: "**GET UP AND MOVE!** :person_walking:"
