templates:
  - name: resource options
    artifacthub-defaults: &artifacthub-defaults
      type: artifacthub
      check_every: 4h

  - name: jobs
    update-helmsman-dsf-config: &update-helmsman-dsf-config
      platform: linux
      image_resource: *yq-image-resource
      inputs:
        - name: chart
        - name: k8s-homelab-repo-pull-main
      outputs:
        - name: chart
        - name: k8s-homelab-repo-pull-main
      run:
        path: /bin/sh
        args:
          - -c
          - |
            set -eu

            ls chart/version
            version=$(cat chart/version)

            echo "setting ${CHART} to ${version}"

            for context in $CONTEXTS; do
              yq -i ".apps.${CHART}.version = \"${version}\"" "k8s-homelab-repo-pull-main/${context}.yaml"
            done
    git-commit-config: &git-commit-config
      platform: linux
      image_resource:
        type: registry-image
        source:
          <<: *docker-creds
          repository: bitnami/git
          tag: latest
      inputs:
        - name: chart
        - name: concourse-pipelines-repo
        - name: k8s-homelab-repo-pull-main
      outputs:
        - name: k8s-homelab-repo-pull-main
      run:
        dir: k8s-homelab-repo-pull-main
        path: /bin/sh
        args:
          - -c
          - |
            set -eu

            ../concourse-pipelines-repo/common/scripts/setup-git-config.sh

            git --no-pager diff
            git add .

            message="${CHART} chart version $(cat ../chart/version)"
            echo "Commit message: ${message}"
            git commit -m "$message"

resource_types:
  - name: artifacthub
    type: docker-image
    source:
      repository: ghcr.io/hdisysteme/artifacthub-resource
      tag: latest

resources:
  - *concourse-pipelines-repo

  - name: k8s-homelab-repo-pull-main
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      <<: *github-creds
      branch: main

  - name: k8s-homelab-repo-push-branch
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      <<: *github-creds

  - name: concourse
    <<: *artifacthub-defaults
    source:
      repository_name: concourse
      api_key: ((artifacthub_key))
      package_name: concourse

  - name: influxdb2
    <<: *artifacthub-defaults
    source:
      repository_name: influxdata
      api_key: ((artifacthub_key))
      package_name: influxdb2

  - name: ingress-nginx
    <<: *artifacthub-defaults
    source:
      repository_name: ingress-nginx
      api_key: ((artifacthub_key))
      package_name: ingress-nginx

  - name: k8s-dashboard
    <<: *artifacthub-defaults
    source:
      repository_name: k8s-dashboard
      api_key: ((artifacthub_key))
      package_name: kubernetes-dashboard

  - name: nextcloud
    <<: *artifacthub-defaults
    source:
      repository_name: nextcloud
      api_key: ((artifacthub_key))
      package_name: nextcloud

  - name: postgresql
    <<: *artifacthub-defaults
    source:
      repository_name: bitnami
      api_key: ((artifacthub_key))
      package_name: postgresql

  - name: redis
    <<: *artifacthub-defaults
    source:
      repository_name: bitnami
      api_key: ((artifacthub_key))
      package_name: redis

groups:
  - name: concourse
    jobs:
      - concourse
  - name: influxdb2
    jobs:
      - influxdb2
  - name: ingress-nginx
    jobs:
      - ingress-nginx
  - name: k8s-dashboard
    jobs:
      - k8s-dashboard
  - name: nextcloud
    jobs:
      - nextcloud
  - name: postgresql
    jobs:
      - postgresql
  - name: redis
    jobs:
      - redis

jobs:
  - name: concourse
    plan:
      - in_parallel:
        - get: concourse
          trigger: true
        - get: k8s-homelab-repo-pull-main
        - get: concourse-pipelines-repo

      - task: update-helmsman-dsf
        input_mapping:
          chart: concourse
        output_mapping:
          chart: concourse
        config:
          <<: *update-helmsman-dsf-config
          params:
            CHART: concourse
            CONTEXTS: homelab

      - task: git-commit
        input_mapping:
          chart: concourse
        config:
          <<: *git-commit-config
          params:
            CHART: concourse

      - put: k8s-homelab-repo-push-branch
        params:
          repository: k8s-homelab-repo-pull-main
          branch: concourse
          force: true

  - name: influxdb2
    plan:
      - in_parallel:
        - get: influxdb2
          trigger: true
        - get: k8s-homelab-repo-pull-main
        - get: concourse-pipelines-repo

      - task: update-helmsman-dsf
        input_mapping:
          chart: influxdb2
        output_mapping:
          chart: influxdb2
        config:
          <<: *update-helmsman-dsf-config
          params:
            CHART: influxdb2
            CONTEXTS: oracle

      - task: git-commit
        input_mapping:
          chart: influxdb2
        config:
          <<: *git-commit-config
          params:
            CHART: influxdb2

      - put: k8s-homelab-repo-push-branch
        params:
          repository: k8s-homelab-repo-pull-main
          branch: influxdb2
          force: true

  - name: ingress-nginx
    plan:
      - in_parallel:
        - get: ingress-nginx
          trigger: true
        - get: k8s-homelab-repo-pull-main
        - get: concourse-pipelines-repo

      - task: update-helmsman-dsf
        input_mapping:
          chart: ingress-nginx
        output_mapping:
          chart: ingress-nginx
        config:
          <<: *update-helmsman-dsf-config
          params:
            CHART: ingress-nginx
            CONTEXTS: homelab oracle

      - task: git-commit
        input_mapping:
          chart: ingress-nginx
        config:
          <<: *git-commit-config
          params:
            CHART: ingress-nginx

      - put: k8s-homelab-repo-push-branch
        params:
          repository: k8s-homelab-repo-pull-main
          branch: ingress-nginx
          force: true

  - name: k8s-dashboard
    plan:
      - in_parallel:
        - get: k8s-dashboard
          trigger: true
        - get: k8s-homelab-repo-pull-main
        - get: concourse-pipelines-repo

      - task: update-helmsman-dsf
        input_mapping:
          chart: k8s-dashboard
        output_mapping:
          chart: k8s-dashboard
        config:
          <<: *update-helmsman-dsf-config
          params:
            CHART: k8s-dashboard
            CONTEXTS: homelab

      - task: git-commit
        input_mapping:
          chart: k8s-dashboard
        config:
          <<: *git-commit-config
          params:
            CHART: k8s-dashboard

      - put: k8s-homelab-repo-push-branch
        params:
          repository: k8s-homelab-repo-pull-main
          branch: k8s-dashboard
          force: true

  - name: nextcloud
    plan:
      - in_parallel:
        - get: nextcloud
          trigger: true
        - get: k8s-homelab-repo-pull-main
        - get: concourse-pipelines-repo

      - task: update-helmsman-dsf
        input_mapping:
          chart: nextcloud
        output_mapping:
          chart: nextcloud
        config:
          <<: *update-helmsman-dsf-config
          params:
            CHART: nextcloud
            CONTEXTS: homelab

      - task: git-commit
        input_mapping:
          chart: nextcloud
        config:
          <<: *git-commit-config
          params:
            CHART: nextcloud

      - put: k8s-homelab-repo-push-branch
        params:
          repository: k8s-homelab-repo-pull-main
          branch: nextcloud
          force: true

  - name: postgresql
    plan:
      - in_parallel:
        - get: postgresql
          trigger: true
        - get: k8s-homelab-repo-pull-main
        - get: concourse-pipelines-repo

      - task: update-helmsman-dsf
        input_mapping:
          chart: postgresql
        output_mapping:
          chart: postgresql
        config:
          <<: *update-helmsman-dsf-config
          params:
            CHART: postgresql
            CONTEXTS: homelab

      - task: git-commit
        input_mapping:
          chart: postgresql
        config:
          <<: *git-commit-config
          params:
            CHART: postgresql

      - put: k8s-homelab-repo-push-branch
        params:
          repository: k8s-homelab-repo-pull-main
          branch: postgresql
          force: true

  - name: redis
    plan:
      - in_parallel:
        - get: redis
          trigger: true
        - get: k8s-homelab-repo-pull-main
        - get: concourse-pipelines-repo

      - task: update-helmsman-dsf
        input_mapping:
          chart: redis
        output_mapping:
          chart: redis
        config:
          <<: *update-helmsman-dsf-config
          params:
            CHART: redis
            CONTEXTS: homelab

      - task: git-commit
        input_mapping:
          chart: redis
        config:
          <<: *git-commit-config
          params:
            CHART: redis

      - put: k8s-homelab-repo-push-branch
        params:
          repository: k8s-homelab-repo-pull-main
          branch: redis
          force: true
