resource_types:
  - name: git-branches
    type: registry-image
    source:
      repository: aoldershaw/git-branches-resource

resources:
  - name: branches
    type: git-branches
    icon: github
    source:
      <<: *github-creds
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      branch_regex: ^(?!main$).*

  - *concourse-pipelines-repo

jobs:
  - name: set-branch-pipelines
    plan:
      - in_parallel:
        - get: branches
          trigger: true
        - get: concourse-pipelines-repo

      - in_parallel:
        - load_var: branches
          file: branches/branches.json

        - do:
          - *get-secret-key-task
          - task: unencrypt-secrets
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  <<: *docker-creds
                  repository: mozilla/sops
                  tag: latest
              inputs:
                - name: concourse-pipelines-repo
                - name: secrets
              outputs:
                - name: secrets
              run:
                path: /bin/sh
                args:
                  - -c
                  - >
                    concourse-pipelines-repo/common/scripts/import-secret-key.sh &&
                    sops -d --output secrets/secrets.yml concourse-pipelines-repo/common/vars/secrets.enc.yml

      - task: build-pipeline-template
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              <<: *docker-creds
              repository: busybox
              tag: latest
          inputs:
            - name: concourse-pipelines-repo
          outputs:
            - name: concourse-pipelines-repo
          run:
            path: /bin/sh
            args:
              - -c
              - mkdir -p compiled-pipelines && cat common/reusable-blocks.yml k8s-homelab/common.yml k8s-homelab/diff-k8s-homelab.yml > compiled-pipelines/diff-k8s-homelab.yml
            dir: concourse-pipelines-repo

      - across:
        - var: branch
          values: ((.:branches))
          max_in_flight: all
        set_pipeline: k8s-homelab-diff
        file: concourse-pipelines-repo/compiled-pipelines/diff-k8s-homelab.yml
        vars:
          branch: ((.:branch.name))
        var_files:
          - secrets/secrets.yml
