resource_types:
  - *webhook-resource-type

resources:
  - *discord-general

  - name: k8s-homelab-repo
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      branch: main
      <<: *github-creds
      ignore_paths:
        - Makefile
        - README.md
        - .gitignore
        - renovate.json

  - *concourse-pipelines-repo

jobs:
  - name: deploy-homelab
    serial: true
    plan:
      - in_parallel: *get-k8s-homelab-in-parrallel

      - task: get-secret-key
        file: concourse-pipelines-repo/common/tasks/get-bw-secret.yml
        params: *bitwarden-params

      - task: deploy-homelab-k8s
        config:
          <<: *helmsman-task-config
          params:
            ACTION: -apply
            KUBE_CONTEXT: homelab
            REPO_DIR: k8s-homelab-repo

    <<: *job-notifications

  - name: deploy-oracle
    serial: true
    plan:
      - in_parallel: *get-k8s-homelab-in-parrallel

      - task: get-secret-key
        file: concourse-pipelines-repo/common/tasks/get-bw-secret.yml
        params: *bitwarden-params

      - task: deploy-oracle-k8s
        config:
          <<: *helmsman-task-config
          params:
            ACTION: -apply
            KUBE_CONTEXT: oracle
            REPO_DIR: k8s-homelab-repo

    <<: *job-notifications
