resource_types:
  - *webhook-resource-type

resources:
  - *discord-deploy

  - name: k8s-homelab-repo
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      branch: main
      <<: *github-creds
      ignore_paths:
        - Makefile
        - README.md
        - .gitignore

  - *concourse-pipelines-repo

jobs:
  - name: deploy-homelab
    serial: true
    plan:
      - in_parallel: *get_in_parrallel

      - *get-secret-key-task

      - task: deploy-homelab-k8s
        config:
          <<: *helmsman_task_config
          params:
            ACTION: -apply
            KUBE_CONTEXT: homelab
            REPO_DIR: k8s-homelab-repo

    <<: *deploy-job-notifications

  - name: deploy-oracle
    serial: true
    plan:
      - in_parallel: *get_in_parrallel

      - *get-secret-key-task

      - task: deploy-oracle-k8s
        config:
          <<: *helmsman_task_config
          params:
            ACTION: -apply
            KUBE_CONTEXT: oracle
            REPO_DIR: k8s-homelab-repo

    <<: *deploy-job-notifications
