resource_types:
  - *webhook-resource-type

resources:
  - *discord-general

  - name: tf-playground-repo
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/tf-playground.git
      branch: main
      <<: *github-creds
      ignore_paths:
        - README.md
        - .gitignore
        - renovate.json

  - *concourse-pipelines-repo

  - name: &weekly weekly
    type: time
    icon: timer-outline
    check_every: 24h
    source:
      days: [Friday]

jobs:
  - name: terraform-plan
    serial: true
    plan:
      - in_parallel:
        - get: tf-playground-repo
          trigger: true
        - get: concourse-pipelines-repo
        - get: *weekly
          trigger: true

      - task: get-tf-variables
        file: concourse-pipelines-repo/common/tasks/get-bw-secret.yml
        vars: *docker-creds
        params:
          BW_ITEMS: ((bitwarden_tf_vars_item_id)):terraform.tfvars ((bitwarden_tf_backend_item_id)):backend.tf
          BW_SERVER: ((bitwarden_server))
          BW_USERNAME: ((bitwarden_username))
          BW_PASSWORD: ((bitwarden_password))

      - task: tf-plan
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              <<: *docker-creds
              repository: hashicorp/terraform
              tag: 1.4.0
          inputs:
            - name: tf-playground-repo
            - name: secrets
          run:
            dir: tf-playground-repo/homelab
            path: /bin/sh
            args:
              - -c
              - |
                set -eu

                cp ../../secrets/terraform.tfvars terraform.tfvars
                cp ../../secrets/backend.tf backend.tf

                terraform init
                terraform validate
                terraform fmt -recursive -check -diff .
                terraform plan -lock=false -detailed-exitcode

    <<: *job-notifications
