resource_types:
  - *webhook-resource-type

resources:
  - *discord-general

  # Repo to pull for building image
  - name: &site-repo personal-website-repo
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/personal-website.git
      branch: main
      <<: *github-creds
      ignore_paths:
        - Makefile
        - README.md
        - .gitignore
        - renovate.json

  - *concourse-pipelines-repo

  # Where we will push the image to
  - name: &docker-repo docker-hub-repo
    type: registry-image
    icon: docker
    source:
      repository: flipenergy/flipenergy
      <<: *docker-creds
      tag: latest

jobs:
  - name: build-and-push-image
    serial: true
    plan:
      - get: *site-repo
        trigger: true

      - task: gen-static-site
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              <<: *docker-creds
              repository: klakegg/hugo
              tag: alpine
          inputs:
            - name: *site-repo
          outputs:
            - name: *site-repo
          run:
            dir: *site-repo
            path: sh
            args:
              - -ec
              - >
                cd flipenergy && hugo && cp -r public ../public

      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource: *oci-build-image-resource
          inputs:
            - name: *site-repo
          outputs:
            - name: image
          params:
            CONTEXT: *site-repo
            IMAGE_PLATFORM: linux/arm64
          run:
            path: build

      - put: *docker-repo
        params:
          image: image/image.tar
          additional_tags: personal-website-repo/.git/short_ref

    on_error: *notify-deploy-failure
    on_failure: *notify-deploy-failure

  - name: deploy-website-to-k8s
    serial: true
    plan:
      - in_parallel:
        - get: *site-repo
          passed: [build-and-push-image]
        - get: *docker-repo
          trigger: true
          passed: [build-and-push-image]
        - get: concourse-pipelines-repo

      - task: get-secret-key
        file: concourse-pipelines-repo/common/tasks/get-bw-secret.yml

      - task: deploy-to-k8s
        config:
          platform: linux
          image_resource: *helmsman-image-resource
          inputs:
            - name: *site-repo
            - name: concourse-pipelines-repo
            - name: secrets
          params:
            KUBE_CONTEXT: oracle
            REPO_DIR: *site-repo
          run:
            path: concourse-pipelines-repo/personal-website/deploy-to-k8s.sh

    <<: *job-notifications
