resource_types:
  - *webhook-resource-type

resources:
  - *discord

  # Repo to pull for building image
  - name: personal-website-repo
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/personal-website.git
      branch: main
      username: ((github_username))
      password: ((github_password))
  - *concourse-pipelines-repo

  # Where we will push the image to
  - name: docker-hub-repo
    type: registry-image
    icon: docker
    source:
      repository: flipenergy/flipenergy
      username: ((docker_hub_username))
      password: ((docker_hub_password))
      tag: latest

jobs:
  - name: build-and-push-image
    serial: true
    plan:
      - get: personal-website-repo
        trigger: true

      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource: *oci-build-image-resource

          inputs:
            - name: personal-website-repo

          outputs:
            - name: image

          params:
            CONTEXT: personal-website-repo
          run:
            path: build

      - put: docker-hub-repo
        params:
          image: image/image.tar
          additional_tags: personal-website-repo/.git/short_ref

    on_error: *notify-failure
    on_failure: *notify-failure

  - name: deploy-website-to-k8s
    serial: true
    plan:
      - in_parallel:
        - get: personal-website-repo
          passed: [build-and-push-image]
        - get: docker-hub-repo
          trigger: true
          passed: [build-and-push-image]
        - get: concourse-pipelines-repo

      - *get_secret_key_task

      - task: deploy-to-k8s
        config:
          platform: linux
          image_resource: *helmsman-image-resource

          inputs:
            - name: personal-website-repo
            - name: concourse-pipelines-repo
            - name: secrets

          params:
            PIHOLE_SERVER_IP: ((pihole_server_ip))

          run:
            path: concourse-pipelines-repo/personal-website/deploy-to-k8s.sh

    <<: *job_notifications
