platform: linux

image_resource:
  type: registry-image
  source:
    username: ((docker_hub_username))
    password: ((docker_hub_password))
    repository: flipenergy/bitwarden-cli
    tag: latest

inputs:
  - name: concourse-pipelines-repo

outputs:
  - name: concourse-pipelines-repo
  - name: secrets

params:
  BW_ITEM: ((bitwarden_gpg_key_item_id))
  BW_SERVER: ((bitwarden_server))
  BW_USERNAME: ((bitwarden_username))
  BW_PASSWORD: ((bitwarden_password))

run:
  path: concourse-pipelines-repo/common/scripts/get-secret-key.sh
