platform: linux

image_resource:
  type: registry-image
  source:
    username: ((username))
    password: ((password))
    repository: flipenergy/bitwarden-cli
    tag: latest

inputs:
  - name: concourse-pipelines-repo

outputs:
  - name: concourse-pipelines-repo
  - name: secrets

run:
  path: concourse-pipelines-repo/common/scripts/get-bw-item.sh
