resource_types:
  - *webhook-resource-type

resources:
  - *discord-info

  - name: k8s-homelab-repo
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      branch: ((branch))
      <<: *github-creds

  - name: k8s-homelab-repo-main
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      branch: main
      <<: *github-creds

  - *concourse-pipelines-repo

# begin job templates
notify-branch-failure: &notify-branch-failure
  put: discord-info
  params:
    message: "**DIFF FAILED** :x: **[((branch))/${BUILD_JOB_NAME}/${BUILD_NAME}](${BUILD_URL}?vars.branch=\"((branch))\")**"

branch-job-notifications: &branch-job-notifications
  on_success:
    put: discord-info
    params:
      message: "**DIFF** :new: **[((branch))/${BUILD_JOB_NAME}/${BUILD_NAME}](${BUILD_URL}?vars.branch=\"((branch))\")**"
  on_error: *notify-branch-failure
  on_failure: *notify-branch-failure

# end job templates

jobs:
  - name: diff-homelab
    serial: true
    plan:
      - in_parallel: *get-k8s-homelab-in-parrallel

      - *get-secret-key-task

      - task: diff-homelab-k8s
        config:
          <<: *helmsman-task-config
          params:
            ACTION: -show-diff
            KUBE_CONTEXT: homelab
            REPO_DIR: k8s-homelab-repo

    <<: *branch-job-notifications

  - name: diff-oracle
    serial: true
    plan:
      - in_parallel: *get-k8s-homelab-in-parrallel

      - *get-secret-key-task

      - task: diff-oracle-k8s
        config:
          <<: *helmsman-task-config
          params:
            ACTION: -show-diff
            KUBE_CONTEXT: oracle
            REPO_DIR: k8s-homelab-repo

    <<: *branch-job-notifications

  - name: cherry-pick-to-main
    serial: true
    plan:
      - in_parallel:
        - get: concourse-pipelines-repo
          passed: [diff-homelab, diff-oracle]
        - get: k8s-homelab-repo-main

      - task: git-cherry-pick
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              <<: *docker-creds
              repository: bitnami/git
              tag: latest
          inputs:
            - name: concourse-pipelines-repo
            - name: k8s-homelab-repo-main
          outputs:
            - name: k8s-homelab-repo-main
          run:
            dir: k8s-homelab-repo-main
            path: /bin/sh
            args:
              - -c
              - |
                ../concourse-pipelines-repo/common/scripts/setup-and-git-add.sh
                git fetch origin ((branch))
                git log -n 1 origin/((branch))
                git cherry-pick origin/((branch))

      - put: k8s-homelab-repo-main
        params:
          repository: k8s-homelab-repo-main
          branch: main
