resource_types:
  - *webhook-resource-type

resources:
  - *discord-info

  - name: k8s-homelab-repo
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      branch: ((branch))
      <<: *github-creds

  - *concourse-pipelines-repo

# begin job templates
notify-branch-failure: &notify-branch-failure
  put: discord-info
  params:
    message: "**FAILED** :x: **[${BUILD_PIPELINE_NAME}/((branch))/${BUILD_JOB_NAME}/${BUILD_NAME}](${BUILD_URL}?vars.branch=\"((branch))\")**"

branch-job-notifications: &branch-job-notifications
  on_success:
    put: discord-info
    params:
      message: "**SUCCESS** :white_check_mark: **[${BUILD_PIPELINE_NAME}/((branch))/${BUILD_JOB_NAME}/${BUILD_NAME}](${BUILD_URL}?vars.branch=\"((branch))\")**"
  on_error: *notify-branch-failure
  on_failure: *notify-branch-failure

# end job templates

jobs:
  - name: diff-homelab
    serial: true
    plan:
      - in_parallel: *get_in_parrallel

      - *get-secret-key-task

      - task: diff-homelab-k8s
        config:
          <<: *helmsman_task_config
          params:
            ACTION: -show-diff
            KUBE_CONTEXT: homelab
            REPO_DIR: k8s-homelab-repo

    <<: *branch-job-notifications

  - name: diff-oracle
    serial: true
    plan:
      - in_parallel: *get_in_parrallel

      - *get-secret-key-task

      - task: diff-oracle-k8s
        config:
          <<: *helmsman_task_config
          params:
            ACTION: -show-diff
            KUBE_CONTEXT: oracle
            REPO_DIR: k8s-homelab-repo

    <<: *branch-job-notifications
