resource_types:
  - *mattermost-resouce-type

resources:
  - *mattermost-resource

  - name: bitwarden-cli-github-release
    type: github-release
    icon: github
    source:
      owner: bitwarden
      repository: cli

  - name: concourse-pipelines-repo
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/concourse-pipelines.git
      branch: master

  # Where we will push the image to
  - name: docker-hub-repo
    type: registry-image
    icon: docker
    source:
      repository: flipenergy/bitwarden_cli
      username: ((docker_hub_username))
      password: ((docker_hub_password))
      tag: latest

jobs:
## Release image build and push job
  - name: build-and-push-bitwarden-cli-image
    serial: true
    plan:
      - in_parallel:
        - get: bitwarden-cli-github-release
          trigger: true
        - get: concourse-pipelines-repo

      - task: build-image
        privileged: true
        config: 
          platform: linux
          image_resource: *oci-build-image-resource

          inputs:
            - name: bitwarden-cli-github-release
            - name: concourse-pipelines-repo

          outputs:
            - name: image

          params:
            CONTEXT: concourse-pipelines-repo/utilites/bitwarden_cli
          run:
            path: sh
            args:
              - -c
              - BUILD_ARGS_VERSION=$(cat bitwarden-cli-github-release/version) build

      - put: docker-hub-repo
        params:
          image: image/image.tar
          additional_tags: bitwarden-cli-github-release/version

    on_success: *notify-success
    on_error: *notify-failure
    on_failure: *notify-failure
