---

resource_types:
  - name: mattermost-webhook
    type: registry-image
    source:
      repository: arbourd/concourse-slack-alert-resource
      tag: ((mattermost_alert_tag))
      username: ((docker_hub_username))
      password: ((docker_hub_password))

resources:
  - name: k8s-homelab-helm-repo-get
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      branch: gh-pages
      paths:
        - charts

  - name: k8s-homelab-helm-repo-put
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      branch: gh-pages
      username: ((github_username))
      password: ((github_password))

  - name: notify-mattermost
    type: mattermost-webhook
    source:
      url: ((mattermost_webhook_url))

jobs:
  - name: helm-index-and-push
    serial: true
    plan:
      - get: k8s-homelab-helm-repo-get
        trigger: true

      - task: helm-index
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine/helm
              username: ((docker_hub_username))
              password: ((docker_hub_password))

          inputs:
            - name: k8s-homelab-helm-repo-get

          outputs:
            - name: k8s-homelab-helm-repo-get

          run:
            path: helm
            args:
              - repo
              - index
              - .
              - --url
              - https://flipenergy.github.io/k8s-homelab/
            dir: k8s-homelab-helm-repo-get

      - task: git-commit
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine/git
              username: ((docker_hub_username))
              password: ((docker_hub_password))

          inputs:
            - name: k8s-homelab-helm-repo-get

          outputs:
            - name: k8s-homelab-helm-repo-get

          run:
            path: sh
            args:
              - -c
              - |
                #!/bin/bash

                git config user.email "dennis.zhang.nrg@gmail.com"
                git config user.name "Concourse Worker"

                git --no-pager diff

                git add .

                git commit -m "update index.yaml"
            dir: k8s-homelab-helm-repo-get

      - put: k8s-homelab-helm-repo-put
        params:
          repository: k8s-homelab-helm-repo-get

    on_success:
      put: notify-mattermost
      params:
        alert_type: success
        message: Helm Repo Update Successful

    on_failure:
      put: notify-mattermost
      params:
        alert_type: failed
        message: Helm Repo Update Failed
