resource_types:
  - *mattermost-resouce-type

resources:
  - *mattermost-resource

  - name: k8s-homelab-repo
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      branch: master
      username: ((github_username))
      password: ((github_password))

  - name: concourse-pipelines-repo
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/concourse-pipelines.git
      branch: master
      username: ((github_username))
      password: ((github_password))

  - name: k8s-homelab-helm-repo-get
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      branch: gh-pages
      username: ((github_username))
      password: ((github_password))
      paths:
        - charts

  - name: k8s-homelab-helm-repo-put
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      branch: gh-pages
      username: ((github_username))
      password: ((github_password))

jobs:
  - name: deploy-k8s-homelab
    serial: true
    plan:
      - in_parallel:
        - get: k8s-homelab-repo
          trigger: true
        - get: concourse-pipelines-repo

      - task: get-secret-key
        config:
          platform: linux
          image_resource: *bitwarden-cli-image-resource

          inputs:
            - name: concourse-pipelines-repo

          outputs:
            - name: concourse-pipelines-repo
            - name: secrets

          params:
            BW_ITEM: ((bitwarden_item))
            BW_SERVER: ((bitwarden_server))
            BW_USERNAME: ((bitwarden_username))
            BW_PASSWORD: ((bitwarden_password))

          run:
            path: concourse-pipelines-repo/common/scripts/get_secret_key.sh

      - task: deploy-homelab-k8s
        config: 
          platform: linux
          image_resource: *helmsman-image-resource

          inputs:
            - name: k8s-homelab-repo
            - name: concourse-pipelines-repo
            - name: secrets

          run:
            path: concourse-pipelines-repo/k8s_homelab/deploy_k8s_homelab.sh

    on_success: *notify-success
    on_error: *notify-failure
    on_failure: *notify-failure
      

  - name: helm-index-and-push
    serial: true
    plan:
      - in_parallel:
        - get: k8s-homelab-helm-repo-get
          trigger: true
        - get: concourse-pipelines-repo

      - task: helm-index
        config:
          platform: linux
          image_resource: *helm-image-resource

          inputs:
            - name: k8s-homelab-helm-repo-get

          outputs:
            - name: k8s-homelab-helm-repo-get

          run:
            path: helm
            args:
              - repo
              - index
              - .
              - --url
              - https://flipenergy.github.io/k8s-homelab/
            dir: k8s-homelab-helm-repo-get

      - task: git-commit
        config:
          platform: linux
          image_resource: *git-image-resource

          inputs:
            - name: k8s-homelab-helm-repo-get
            - name: concourse-pipelines-repo

          outputs:
            - name: k8s-homelab-helm-repo-get

          run:
            path: sh
            args:
              - -ec
              - |
                ../concourse-pipelines-repo/common/scripts/setup_and_git_add.sh
                git commit -m "CONCOURSE: update index.yaml"

            dir: k8s-homelab-helm-repo-get

      - put: k8s-homelab-helm-repo-put
        params:
          repository: k8s-homelab-helm-repo-get

    on_success: *notify-success
    on_error: *notify-failure
    on_failure: *notify-failure
