resource_types:
  - *webhook-resource-type

resources:
  - *discord

  - name: k8s-homelab-repo
    type: git
    icon: github
    source:
      uri: https://github.com/FlipEnergy/k8s-homelab.git
      branch: master
      username: ((github_username))
      password: ((github_password))
      ignore_paths:
        - Makefile
        - README.md
        - .gitignore
  - *concourse-pipelines-repo

jobs:
  - name: deploy-k8s-homelab
    serial: true
    plan:
      - in_parallel:
        - get: k8s-homelab-repo
          trigger: true
        - get: concourse-pipelines-repo

      - task: get-secret-key
        config:
          platform: linux
          image_resource: *bitwarden-cli-image-resource

          inputs:
            - name: concourse-pipelines-repo

          outputs:
            - name: concourse-pipelines-repo
            - name: secrets

          params:
            BW_ITEM: ((bitwarden_item))
            BW_SERVER: ((bitwarden_server))
            BW_USERNAME: ((bitwarden_username))
            BW_PASSWORD: ((bitwarden_password))

          run:
            path: concourse-pipelines-repo/common/scripts/get_secret_key.sh

      - task: deploy-homelab-k8s
        config:
          platform: linux
          image_resource: *helmsman-image-resource

          inputs:
            - name: k8s-homelab-repo
            - name: concourse-pipelines-repo
            - name: secrets

          params:
            PIHOLE_SERVER_IP: ((pihole_server_ip))

          run:
            path: concourse-pipelines-repo/k8s_homelab/deploy_k8s_homelab.sh

    on_success: *notify-success
    on_error: *notify-failure
    on_failure: *notify-failure
