# begin resource templates
github_resource_options: &github_resource_options
  type: github-release
  icon: github
  check_every: 30m

image_resource_options: &image_resource_options
  type: registry-image
  icon: docker
# end resource templates

resource_types:
  - *webhook-resource-type

resources:
  - *discord_general

  - name: &ci_repo container-images-repo
    type: git
    icon: github
    source:
      <<: *github_creds
      uri: https://github.com/FlipEnergy/container-images.git
      branch: main

  # Bitwarden-cli
  - name: &bitwarden_release bitwarden-cli-github-release
    <<: *github_resource_options
    source:
      <<: *github_access_token
      owner: bitwarden
      repository: cli

  - name: &bitwarden_docker bitwarden-cli-docker-repo
    <<: *image_resource_options
    source:
      <<: *docker_creds
      repository: flipenergy/bitwarden-cli
      tag: latest

  # Restic-with-curl
  - name: &restic_release restic-upstream-repo
    <<: *image_resource_options
    check_every: 30m
    source:
      <<: *docker_creds
      repository: restic/restic

  - name: &restic_docker restic-docker-repo
    <<: *image_resource_options
    source:
      <<: *docker_creds
      repository: flipenergy/restic
      tag: latest

  # yq
  - name: &yq_release yq-github-release
    <<: *github_resource_options
    source:
      <<: *github_access_token
      owner: mikefarah
      repository: yq

  - name: &yq_docker yq-ubuntu-docker-repo
    <<: *image_resource_options
    source:
      <<: *docker_creds
      repository: flipenergy/yq-ubuntu
      tag: latest

# begin job templates
release_get_options: &release_get_options
  trigger: true
  params:
    globs:
      - none

build_image_params: &build_image_params
  CI_REPO_DIR: *ci_repo
  BUILD_ARGS_FILE: build_args_file

build_image_config: &build_image_config
  platform: linux
  image_resource: *oci-build-image-resource
  outputs:
    - name: image
  run:
    path: sh
    args:
      - -ec
      - |
        echo VERSION=$(cat ${VERSION_DIR_PATH}/${VERSION_FILE}) > build_args_file \
          && export CONTEXT=${CI_REPO_DIR}/${DOCKER_CONTEXT_DIR} \
          && build

put_image_params: &put_image_params
  image: image/image.tar
# end job templates

jobs:
  - name: bitwarden-cli-image
    serial: true
    plan:
      - in_parallel:
        - get: *bitwarden_release
          <<: *release_get_options
        - get: *ci_repo

      - task: build-image
        privileged: true
        config:
          <<: *build_image_config
          inputs:
            - name: *bitwarden_release
            - name: *ci_repo
          params:
            <<: *build_image_params
            DOCKER_CONTEXT_DIR: bitwarden-cli
            VERSION_DIR_PATH: *bitwarden_release
            VERSION_FILE: version

      - put: *bitwarden_docker
        params:
          <<: *put_image_params
          additional_tags: bitwarden-cli-github-release/version

    <<: *job_notifications

  - name: restic-image
    serial: true
    plan:
      - in_parallel:
        - get: *restic_release
          trigger: true
        - get: *ci_repo

      - task: build-image
        privileged: true
        config:
          <<: *build_image_config
          inputs:
            - name: *restic_release
            - name: *ci_repo
          params:
            <<: *build_image_params
            DOCKER_CONTEXT_DIR: restic-with-curl
            VERSION_DIR_PATH: *restic_release
            VERSION_FILE: tag

      - put: *restic_docker
        params:
          <<: *put_image_params
          additional_tags: restic-upstream-repo/tag

    <<: *job_notifications

  - name: yq-ubuntu-image
    serial: true
    plan:
      - in_parallel:
        - get: *yq_release
          <<: *release_get_options
        - get: *ci_repo

      - task: build-image
        privileged: true
        config:
          <<: *build_image_config
          inputs:
            - name: *yq_release
            - name: *ci_repo
          params:
            <<: *build_image_params
            DOCKER_CONTEXT_DIR: yq-ubuntu
            VERSION_DIR_PATH: *yq_release
            VERSION_FILE: version

      - put: *yq_docker
        params:
          <<: *put_image_params
          additional_tags: yq-github-release/version

    <<: *job_notifications
